### ISSUE TITLE
Unable to resize the image for non square image size

### ISSUE THREAD

**Issue by sparupat** [thinksoftware/meteor-image-resize-client#1]
Hi, 

The resize method always resizes the image to square image dimensions, although I provide non square dimensions.

e.g
Resizer.resize(files[0], {
            width: 200,
            height: 600,
            cropSquare: false
        }, function(err, url) {});

**Comment by aaronthorp** [comment]
hmm, seems you are correct, i shall fix that and release an update shortly

**Comment by sparupat** [comment]
I used the below snippet to fix the resize issue

resizeCanvas.width = options.width;
resizeCanvas.height = options.height;
var resize_ctx = resizeCanvas.getContext("2d");
resize_ctx.drawImage(resize_img, 0, 0, options.width, options.height);
var resize_dataUrl = resizeCanvas.toDataURL(fileData.type);

**Comment by timbrandin** [comment]
You should check out [this PR](https://github.com/thinksoftware/meteor-image-resize-client/pull/5) if it solves this issue, it contains a refactor to more battle tested javascript library for image resizing in the client: [JavaScript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image/)

**Comment by timbrandin** [comment]
Please try the latest version, this is probably solved now.

**Comment by subatomicceo** [comment]
I'm still experiencing this issue even after setting {cropSquare:false}. Thoughts?

**Comment by egarza54** [comment]
Can this issue be resolved? I'm currently having trouble uploading non-square images
